/* The following code was generated by JFlex 1.3.5 on 2/20/08 2:21 PM */

/*
 * File          : policy.flex
 * Project       : jlift-frontend
 * Description   : Lexer for Policy File
 * Author(s)     : dhking
 *
 * Created       : Feb 8, 2008 6:14:02 PM 
 *
 * Copyright (c) 2007-2008 The Pennsylvania State University
 * Systems and Internet Infrastructure Security Laboratory
 *
 */

package jliftfrontend.policy.parse;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 2/20/08 2:21 PM from the specification file
 * <tt>file:/home/dhking/workspace/jif/jlift-frontend/src/jliftfrontend/policy/parse/policy.flex</tt>
 */
public class PolicyLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int END_OF_LINE_COMMENT = 2;
  final public static int BLOCK_COMMENT = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     5,  5,  5,  5,  5,  5,  5,  5,  5,  3,  2,  0,  3,  1,  5,  5, 
     5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  0,  0,  0,  0, 
     3,  0,  0,  0,  4,  0,  0,  0, 14, 15,  8,  0, 18,  0,  6,  7, 
     5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 16,  9,  0, 17,  0,  0, 
     0,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 12,  0, 13,  0,  4, 
     0, 20, 21, 32, 37, 22, 36, 26, 38, 27,  4,  4, 19, 25, 28, 33, 
    23,  4, 24, 34, 29, 30, 31,  4,  4, 35,  4, 10,  0, 11,  0,  5
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    39,    78,   117,   156,   117,   195,   117,   234,   117, 
      117,   117,   117,   117,   117,   117,   117,   273,   117,   312, 
      351,   390,   429,   468,   507,   546,   585,   624,   117,   663, 
      117,   117,   702,   741,   780,   819,   858,   897,   936,   975, 
     1014,  1053,  1092,  1131,  1170,   117,  1209,  1248,  1287,  1326, 
     1365,  1404,  1443,  1482,  1521,  1560,  1599,  1638,  1677,  1716, 
     1755,  1794,  1833,  1872,  1911,  1950,  1989,  2028,   195,   195, 
     2067,   195,   195,  2106,  2145,  2184,   195,  2223,   195,  2262, 
     2301,  2340,   195,  2379,  2418,  2457,  2496,  2535,  2574,  2613, 
     2652,  2691,   195,   195,  2730,  2769,  2808,  2847,   195,   195
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\4\1\5\2\6\1\7\1\4\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\4\1\23\1\24\1\25\1\26\1\7\1\27\1\30"+
    "\1\31\6\7\1\32\3\7\1\33\2\7\10\6\1\34"+
    "\40\6\1\35\44\6\51\0\1\6\50\0\2\7\1\36"+
    "\14\0\24\7\7\0\1\37\1\40\56\0\1\41\32\0"+
    "\2\7\1\36\14\0\1\7\1\42\14\7\1\43\5\7"+
    "\4\0\2\7\1\36\14\0\5\7\1\44\16\7\4\0"+
    "\2\7\1\36\14\0\3\7\1\45\20\7\4\0\2\7"+
    "\1\36\14\0\1\7\1\46\3\7\1\47\16\7\4\0"+
    "\2\7\1\36\14\0\3\7\1\50\20\7\4\0\2\7"+
    "\1\36\14\0\3\7\1\51\20\7\4\0\2\7\1\36"+
    "\14\0\1\52\15\7\1\53\5\7\4\0\2\7\1\36"+
    "\14\0\10\7\1\54\13\7\7\0\1\35\43\0\1\55"+
    "\16\0\24\55\21\0\1\56\31\0\2\7\1\36\14\0"+
    "\2\7\1\57\21\7\4\0\2\7\1\36\14\0\15\7"+
    "\1\60\6\7\4\0\2\7\1\36\14\0\5\7\1\61"+
    "\16\7\4\0\2\7\1\36\14\0\7\7\1\62\14\7"+
    "\4\0\2\7\1\36\14\0\5\7\1\63\16\7\4\0"+
    "\2\7\1\36\14\0\10\7\1\64\13\7\4\0\2\7"+
    "\1\36\14\0\12\7\1\65\11\7\4\0\2\7\1\36"+
    "\14\0\12\7\1\66\11\7\4\0\2\7\1\36\14\0"+
    "\1\7\1\67\22\7\4\0\2\7\1\36\14\0\11\7"+
    "\1\70\12\7\4\0\2\7\1\36\14\0\3\7\1\71"+
    "\20\7\4\0\2\55\1\36\14\0\24\55\4\0\2\7"+
    "\1\36\14\0\3\7\1\72\20\7\4\0\2\7\1\36"+
    "\14\0\1\7\1\73\22\7\4\0\2\7\1\36\14\0"+
    "\1\7\1\74\22\7\4\0\2\7\1\36\14\0\10\7"+
    "\1\75\13\7\4\0\2\7\1\36\14\0\1\7\1\76"+
    "\22\7\4\0\2\7\1\36\14\0\11\7\1\77\12\7"+
    "\4\0\2\7\1\36\14\0\13\7\1\100\10\7\4\0"+
    "\2\7\1\36\14\0\23\7\1\101\4\0\2\7\1\36"+
    "\14\0\17\7\1\102\4\7\4\0\2\7\1\36\14\0"+
    "\17\7\1\103\4\7\4\0\2\7\1\36\14\0\1\104"+
    "\23\7\4\0\2\7\1\36\14\0\1\105\23\7\4\0"+
    "\2\7\1\36\14\0\1\106\23\7\4\0\2\7\1\36"+
    "\14\0\20\7\1\107\3\7\4\0\2\7\1\36\14\0"+
    "\11\7\1\110\12\7\4\0\2\7\1\36\14\0\6\7"+
    "\1\111\15\7\4\0\2\7\1\36\14\0\15\7\1\112"+
    "\6\7\4\0\2\7\1\36\14\0\5\7\1\113\16\7"+
    "\4\0\2\7\1\36\14\0\16\7\1\114\5\7\4\0"+
    "\2\7\1\36\14\0\17\7\1\115\4\7\4\0\2\7"+
    "\1\36\14\0\12\7\1\116\11\7\4\0\2\7\1\36"+
    "\14\0\22\7\1\117\1\7\4\0\2\7\1\36\14\0"+
    "\2\7\1\120\21\7\4\0\2\7\1\36\14\0\10\7"+
    "\1\121\13\7\4\0\2\7\1\36\14\0\11\7\1\122"+
    "\12\7\4\0\2\7\1\36\14\0\22\7\1\123\1\7"+
    "\4\0\2\7\1\36\14\0\5\7\1\124\16\7\4\0"+
    "\2\7\1\36\14\0\1\7\1\125\22\7\4\0\2\7"+
    "\1\36\14\0\4\7\1\126\17\7\4\0\2\7\1\36"+
    "\14\0\14\7\1\127\7\7\4\0\2\7\1\36\14\0"+
    "\13\7\1\130\10\7\4\0\2\7\1\36\14\0\17\7"+
    "\1\131\4\7\4\0\2\7\1\36\14\0\1\7\1\132"+
    "\22\7\4\0\2\7\1\36\14\0\1\7\1\133\22\7"+
    "\4\0\2\7\1\36\14\0\15\7\1\134\6\7\4\0"+
    "\2\7\1\36\14\0\3\7\1\135\20\7\4\0\2\7"+
    "\1\36\14\0\1\136\23\7\4\0\2\7\1\36\14\0"+
    "\1\137\23\7\4\0\2\7\1\36\14\0\12\7\1\140"+
    "\11\7\4\0\2\7\1\36\14\0\13\7\1\141\10\7"+
    "\4\0\2\7\1\36\14\0\16\7\1\142\5\7\4\0"+
    "\2\7\1\36\14\0\3\7\1\143\20\7\4\0\2\7"+
    "\1\36\14\0\5\7\1\144\16\7";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  9,  1,  9,  1,  9,  1,  9,  9,  9,  9,  9,  9,  9, 
     9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  0,  9,  9, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PolicyLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public PolicyLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2886];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 99: 
          {  return symbol( Symbols.CONSTRUCTOR );  }
        case 101: break;
        case 98: 
          {  return symbol( Symbols.RETURNVALUE );  }
        case 102: break;
        case 30: 
          {  yybegin(END_OF_LINE_COMMENT);  }
        case 103: break;
        case 28: 
          {  yybegin(YYINITIAL);  }
        case 104: break;
        case 78: 
          {  return symbol( Symbols.FIELD );  }
        case 105: break;
        case 76: 
          {  return symbol( Symbols.CLASS );  }
        case 106: break;
        case 72: 
          {  return symbol( Symbols.PARAM );  }
        case 107: break;
        case 71: 
          {  return symbol( Symbols.BEGIN );  }
        case 108: break;
        case 69: 
          {  return symbol( Symbols.LOCAL );  }
        case 109: break;
        case 68: 
          {  return symbol( Symbols.LABEL );  }
        case 110: break;
        case 10: 
          {  return symbol( Symbols.SEMI );  }
        case 111: break;
        case 9: 
          {  return symbol( Symbols.STAR );  }
        case 112: break;
        case 13: 
          {  return symbol( Symbols.LBRACK);  }
        case 113: break;
        case 14: 
          {  return symbol( Symbols.RBRACK);  }
        case 114: break;
        case 17: 
          {  return symbol( Symbols.COLON );  }
        case 115: break;
        case 18: 
          {  return symbol( Symbols.COMMA );  }
        case 116: break;
        case 45: 
          {  return symbol( Symbols.DEF );  }
        case 117: break;
        case 7: 
          {  return symbol( Symbols.DOT );  }
        case 118: break;
        case 6: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 43: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 70: 
        case 73: 
        case 74: 
        case 75: 
        case 77: 
        case 79: 
        case 80: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 94: 
        case 95: 
        case 96: 
        case 97: 
          {  return symbol( Symbols.ID, new String( yytext() ) );  }
        case 119: break;
        case 3: 
        case 8: 
          {  throw new Error("Illegal character <"+
                                                    yytext()+"> at line " + (yyline + 1) + ", column " + yycolumn);  }
        case 120: break;
        case 82: 
          {  return symbol( Symbols.METHOD );  }
        case 121: break;
        case 81: 
          {  return symbol( Symbols.RETURN );  }
        case 122: break;
        case 12: 
          {  return symbol( Symbols.RBRACE );  }
        case 123: break;
        case 11: 
          {  return symbol( Symbols.LBRACE );  }
        case 124: break;
        case 15: 
          {  return symbol( Symbols.LPAREN );  }
        case 125: break;
        case 16: 
          {  return symbol( Symbols.RPAREN );  }
        case 126: break;
        case 31: 
          {  yybegin(BLOCK_COMMENT);  }
        case 127: break;
        case 44: 
          {  return symbol( Symbols.CLASSNAME, new String( yytext() ) );  }
        case 128: break;
        case 4: 
        case 5: 
          {  /* ignore */  }
        case 129: break;
        case 27: 
          {  /* ignore */  }
        case 130: break;
        case 93: 
          {  return symbol( Symbols.PRINCIPAL );  }
        case 131: break;
        case 92: 
          {  return symbol( Symbols.ARRAYBASE );  }
        case 132: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { 	return symbol( Symbols.EOF );
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
