
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 20 15:47:53 EST 2008
//----------------------------------------------------

package jliftfrontend.policy.parse;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int RBRACK = 8;
  public static final int CLASSNAME = 2;
  public static final int CLASS = 13;
  public static final int RBRACE = 6;
  public static final int RPAREN = 10;
  public static final int ARRAYBASE = 23;
  public static final int SEMI = 4;
  public static final int STAR = 19;
  public static final int LOCAL = 16;
  public static final int LBRACK = 7;
  public static final int RETURN = 25;
  public static final int COLON = 18;
  public static final int LPAREN = 9;
  public static final int LBRACE = 5;
  public static final int ID = 3;
  public static final int RETURNVALUE = 26;
  public static final int BEGIN = 24;
  public static final int COMMA = 20;
  public static final int CONSTRUCTOR = 17;
  public static final int EOF = 0;
  public static final int PRINCIPAL = 12;
  public static final int DEF = 11;
  public static final int METHOD = 15;
  public static final int FIELD = 14;
  public static final int DOT = 27;
  public static final int error = 1;
  public static final int PARAM = 22;
  public static final int LABEL = 21;
}

